class CityList {
  List<String> cityList = [
    'Palmas, TO',
    'Araguaína, TO',
    'Gurupi, TO',
    'Porto Nacional, TO',
    'Paraíso do Tocantins, TO',
    'Araguatins, TO',
    'Colinas do Tocantins, TO',
    'Guaraí, TO',
    'Tocantinópolis, TO',
    'Dianópolis, TO',
    'Augustinópolis, TO',
    'Formoso do Araguaia, TO',
    'Miracema do Tocantins, TO',
    'Taguatinga, TO',
    'Lagoa da Confusão, TO',
    'Pedro Afonso, TO',
    'Miranorte, TO',
    'Goiatins, TO',
    'São Miguel do Tocantins, TO',
    'Nova Olinda, TO',
    'Peixe, TO',
    'Wanderlândia, TO',
    'Buriti do Tocantins, TO',
    'Xambioá, TO',
    'Esperantina, TO',
    'Babaçulândia, TO',
    'Campos Lindos, TO',
    'Arraias, TO',
    'Paranã, TO',
    'São Paulo, SP',
    'Guarulhos, SP',
    'Campinas, SP',
    'São Bernardo do Campo, SP',
    'São José dos Campos, SP',
    'Santo André, SP',
    'Ribeirão Preto, SP',
    'Osasco, SP',
    'Sorocaba, SP',
    'Mauá, SP',
    'São José do Rio Preto, SP',
    'Mogi das Cruzes, SP',
    'Santos, SP',
    'Diadema, SP',
    'Jundiaí, SP',
    'Piracicaba, SP',
    'Carapicuíba, SP',
    'Bauru, SP',
    'Itaquaquecetuba, SP',
    'São Vicente, SP',
    'Franca, SP',
    'Praia Grande, SP',
    'Guarujá, SP',
    'Taubaté, SP',
    'Limeira, SP',
    'Suzano, SP',
    'Taboão da Serra, SP',
    'Sumaré, SP',
    'Barueri, SP',
    'Embu das Artes, SP',
    'Indaiatuba, SP',
    'Cotia, SP',
    'São Carlos, SP',
    'Americana, SP',
    'Itapevi, SP',
    'Marília, SP',
    'Araraquara, SP',
    'Hortolândia, SP',
    'Jacareí, SP',
    'Presidente Prudente, SP',
    'Rio Claro, SP',
    'Araçatuba, SP',
    'Ferraz de Vasconcelos, SP',
    'Santa Bárbara dOeste, SP',
    'Itapecerica da Serra, SP',
    'Francisco Morato, SP',
    'Itu, SP',
    'Bragança Paulista, SP',
    'Pindamonhangaba, SP',
    'Itapetininga, SP',
    'São Caetano do Sul, SP',
    'Franco da Rocha, SP',
    'Mogi Guaçu, SP',
    'Jaú, SP',
    'Botucatu, SP',
    'Atibaia, SP',
    'Santana de Parnaíba, SP',
    'Araras, SP',
    'Valinhos, SP',
    'Cubatão, SP',
    'Sertãozinho, SP',
    'Jandira, SP',
    'Birigui, SP',
    'Ribeirão Pires, SP',
    'Caraguatatuba, SP',
    'Votorantim, SP',
    'Várzea Paulista, SP',
    'Itatiba, SP',
    'Tatuí, SP',
    'Barretos, SP',
    'Guaratinguetá, SP',
    'Catanduva, SP',
    'Salto, SP',
    'Poá, SP',
    'Ourinhos, SP',
    'Paulínia, SP',
    'Assis, SP',
    'Leme, SP',
    'Itanhaém, SP',
    'Caieiras, SP',
    'Mairiporã, SP',
    'Votuporanga, SP',
    'Caçapava, SP',
    'Itapeva, SP',
    'Mogi Mirim, SP',
    'São Roque, SP',
    'Ubatuba, SP',
    'Arujá, SP',
    'São João da Boa Vista, SP',
    'Avaré, SP',
    'São Sebastião, SP',
    'Lorena, SP',
    'Campo Limpo Paulista, SP',
    'Matão, SP',
    'Cruzeiro, SP',
    'Vinhedo, SP',
    'Ibiúna, SP',
    'Cajamar, SP',
    'Lins, SP',
    'Jaboticabal, SP',
    'Bebedouro, SP',
    'Pirassununga, SP',
    'Itapira, SP',
    'Cosmópolis, SP',
    'Amparo, SP',
    'Embu-Guaçu, SP',
    'Peruíbe, SP',
    'Fernandópolis, SP',
    'Lençóis Paulista, SP',
    'Mococa, SP',
    'Bertioga, SP',
    'Tupã, SP',
    'Itupeva, SP',
    'Penápolis, SP',
    'Batatais, SP',
    'Boituva, SP',
    'Nova Odessa, SP',
    'Monte Mor, SP',
    'Ibitinga, SP',
    'Mirassol, SP',
    'Jaguariúna, SP',
    'Mongaguá, SP',
    'Santa Isabel, SP',
    'Taquaritinga, SP',
    'Andradina, SP',
    'Capivari, SP',
    'Porto Ferreira, SP',
    'Registro, SP',
    'Artur Nogueira, SP',
    'Piedade, SP',
    'Olímpia, SP',
    'São José do Rio Pardo, SP',
    'Vargem Grande Paulista, SP',
    'Porto Feliz, SP',
    'São Joaquim da Barra, SP',
    'Campos do Jordão, SP',
    'Rio Grande da Serra, SP',
    'Pontal, SP',
    'Cabreúva, SP',
    'Monte Alto, SP',
    'Louveira, SP',
    'Itararé, SP',
    'Cerquilho, SP',
    'Jales, SP',
    'Pedreira, SP',
    'Tremembé, SP',
    'Santa Cruz do Rio Pardo, SP',
    'Mairinque, SP',
    'Pederneiras, SP',
    'Dracena, SP',
    'Capão Bonito, SP',
    'Salto de Pirapora, SP',
    'Paraguaçu Paulista, SP',
    'Serrana, SP',
    'Jardinópolis, SP',
    'Orlândia, SP',
    'Espírito Santo do Pinhal, SP',
    'Presidente Epitácio, SP',
    'Garça, SP',
    'Itápolis, SP',
    'Vargem Grande do Sul, SP',
    'Tietê, SP',
    'Ituverava, SP',
    'Novo Horizonte, SP',
    'Socorro, SP',
    'Américo Brasiliense, SP',
    'São Manuel, SP',
    'Guaíra, SP',
    'Promissão, SP',
    'Guariba, SP',
    'Pitangueiras, SP',
    'Presidente Venceslau, SP',
    'Iperó, SP',
    'José Bonifácio, SP',
    'Agudos, SP',
    'Aguaí, SP',
    'São Pedro, SP',
    'Rio das Pedras, SP',
    'Aparecida, SP',
    'Ilhabela, SP',
    'Barra Bonita, SP',
    'Cravinhos, SP',
    'Bariri, SP',
    'Ibaté, SP',
    'Araçoiaba da Serra, SP',
    'Adamantina, SP',
    'Santa Cruz das Palmeiras, SP',
    'Descalvado, SP',
    'Cachoeira Paulista, SP',
    'Morro Agudo, SP',
    'Barrinha, SP',
    'Biritiba Mirim, SP',
    'Guararapes, SP',
    'Osvaldo Cruz, SP',
    'São Miguel Arcanjo, SP',
    'Santa Fé do Sul, SP',
    'Juquitiba, SP',
    'Cândido Mota, SP',
    'Jarinu, SP',
    'Iguape, SP',
    'Igarapava, SP',
    'Casa Branca, SP',
    'Guararema, SP',
    'Piraju, SP',
    'Mirandópolis, SP',
    'Rancharia, SP',
    'Serra Negra, SP',
    'Pilar do Sul, SP',
    'Laranjal Paulista, SP',
    'Conchal, SP',
    'Cajati, SP',
    'Pirapozinho, SP',
    'Santa Gertrudes, SP',
    'Dois Córregos, SP',
    'Santa Rita do Passa Quatro, SP',
    'Itaí, SP',
    'Piracaia, SP',
    'Valparaíso, SP',
    'Santa Rosa de Viterbo, SP',
    'Ilha Solteira, SP',
    'Martinópolis, SP',
    'Cajuru, SP',
    'Bom Jesus dos Perdões, SP',
    'Tanabi, SP',
    'Pirajuí, SP',
    'Angatuba, SP',
    'Pereira Barreto, SP',
    'Monte Aprazível, SP',
    'Brodowski, SP',
    'Potim, SP',
    'Cordeirópolis, SP',
    'Álvares Machado, SP',
    'Iracemápolis, SP',
    'Brotas, SP',
    'Igaraçu do Tietê, SP',
    'Apiaí, SP',
    'Santo Antônio de Posse, SP',
    'Teodoro Sampaio, SP',
    'Araçariguama, SP',
    'Taquarituba, SP',
    'Tambaú, SP',
    'Miguelópolis, SP',
    'Pompéia, SP',
    'Palmital, SP',
    'Pradópolis, SP',
    'Guapiaçu, SP',
    'Lucélia, SP',
    'Nova Granada, SP',
    'Engenheiro Coelho, SP',
    'Castilho, SP',
    'Guará, SP',
    'Cunha, SP',
    'Capela do Alto, SP',
    'Itatinga, SP',
    'Junqueirópolis, SP',
    'Bastos, SP',
    'Santo Anastácio, SP',
    'Paranapanema, SP',
    'Regente Feijó, SP',
    'Cerqueira César, SP',
    'Buri, SP',
    'Pariquera-Açu, SP',
    'Miracatu, SP',
    'Pirapora do Bom Jesus, SP',
    'Guareí, SP',
    'Viradouro, SP',
    'Caconde, SP',
    'Monte Azul Paulista, SP',
    'Águas de Lindóia, SP',
    'Alumínio, SP',
    'Nazaré Paulista, SP',
    'Juquiá, SP',
    'Itirapina, SP',
    'Colina, SP',
    'Cesário Lange, SP',
    'Mirante do Paranapanema, SP',
    'Paraibuna, SP',
    'Conchas, SP',
    'Elias Fausto, SP',
    'Bady Bassitt, SP',
    'Cafelândia, SP',
    'Jacupiranga, SP',
    'Severínia, SP',
    'Itariri, SP',
    'Potirendaba, SP',
    'Charqueada, SP',
    'Buritama, SP',
    'Itaberá, SP',
    'Pindorama, SP',
    'Salesópolis, SP',
    'Macatuba, SP',
    'Guapiara, SP',
    'Pedregulho, SP',
    'Ipuã, SP',
    'Tabatinga, SP',
    'Borborema, SP',
    'Altinópolis, SP',
    'São Lourenço da Serra, SP',
    'Fartura, SP',
    'Ribeirão Branco, SP',
    'Panorama, SP',
    'Rosana, SP',
    'Tupi Paulista, SP',
    'Santa Adélia, SP',
    'Luís Antônio, SP',
    'Holambra, SP',
    'Eldorado, SP',
    'Pinhalzinho, SP',
    'São Simão, SP',
    'Tarumã, SP',
    'Itajobi, SP',
    'Auriflama, SP',
    'Serra Azul, SP',
    'Itaporanga, SP',
    'Ipaussu, SP',
    'Boa Esperança do Sul, SP',
    'Patrocínio Paulista, SP',
    'Flórida Paulista, SP',
    'Santa Branca, SP',
    'Taguaí, SP',
    'Pacaembu, SP',
    'Quatá, SP',
    'Itapuí, SP',
    'Maracaí, SP',
    'Avanhandava, SP',
    'Urupês, SP',
    'Morungaba, SP',
    'Piratininga, SP',
    'Queluz, SP',
    'Valentim Gentil, SP',
    'Palmares Paulista, SP',
    'Piquete, SP',
    'Joanópolis, SP',
    'Ribeirão Bonito, SP',
    'Palestina, SP',
    'Mineiros do Tietê, SP',
    'Presidente Bernardes, SP',
    'Tapiratiba, SP',
    'Riolândia, SP',
    'Sete Barras, SP',
    'Ibirá, SP',
    'Lavínia, SP',
    'Bocaina, SP',
    'Tabapuã, SP',
    'Cananéia, SP',
    'Duartina, SP',
    'Chavantes, SP',
    'Guaiçara, SP',
    'Cardoso, SP',
    'São Sebastião da Grama, SP',
    'Bofete, SP',
    'Sales Oliveira, SP',
    'Iacanga, SP',
    'Nhandeara, SP',
    'Ilha Comprida, SP',
    'Pirangi, SP',
    'Nova Europa, SP',
    'Pedro de Toledo, SP',
    'Estiva Gerbi, SP',
    'Getulina, SP',
    'Guaraci, SP',
    'Areiópolis, SP',
    'Bernardino de Campos, SP',
    'Bananal, SP',
    'Divinolândia, SP',
    'Parapuã, SP',
    'São Bento do Sapucaí, SP',
    'Roseira, SP',
    'General Salgado, SP',
    'Vargem, SP',
    'Rincão, SP',
    'Vera Cruz, SP',
    'Ouroeste, SP',
    'São Luiz do Paraitinga, SP',
    'Cajobi, SP',
    'Sarapuí, SP',
    'Porangaba, SP',
    'Uchoa, SP',
    'Dumont, SP',
    'Torrinha, SP',
    'Reginópolis, SP',
    'Aracaju, SE',
    'Nossa Senhora do Socorro, SE',
    'Lagarto, SE',
    'Itabaiana, SE',
    'São Cristóvão, SE',
    'Estância, SE',
    'Tobias Barreto, SE',
    'Itabaianinha, SE',
    'Simão Dias, SE',
    'Nossa Senhora da Glória, SE',
    'Poço Redondo, SE',
    'Itaporanga dAjuda, SE',
    'Capela, SE',
    'Barra dos Coqueiros, SE',
    'Canindé de São Francisco, SE',
    'Laranjeiras, SE',
    'Propriá, SE',
    'Porto da Folha, SE',
    'Boquim, SE',
    'Nossa Senhora das Dores, SE',
    'Umbaúba, SE',
    'Poço Verde, SE',
    'Carira, SE',
    'Aquidabã, SE',
    'Salgado, SE',
    'Riachão do Dantas, SE',
    'Japaratuba, SE',
    'Ribeirópolis, SE',
    'Areia Branca, SE',
    'Neópolis, SE',
    'Indiaroba, SE',
    'Campo do Brito, SE',
    'Cristinápolis, SE',
    'Maruim, SE',
    'Carmópolis, SE',
    'Frei Paulo, SE',
    'Monte Alegre de Sergipe, SE',
    'Pacatuba, SE',
    'Santa Luzia do Itanhy, SE',
    'Tomar do Geru, SE',
    'Japoatã, SE',
    'Malhador, SE',
    'Santo Amaro das Brotas, SE',
    'Gararu, SE',
    'Moita Bonita, SE',
    'São Domingos, SE',
    'Rosário do Catete, SE',
    'Riachuelo, SE',
    'Joinville, SC',
    'Florianópolis, SC',
    'Blumenau, SC',
    'São José, SC',
    'Chapecó, SC',
    'Itajaí, SC',
    'Criciúma, SC',
    'Jaraguá do Sul, SC',
    'Palhoça, SC',
    'Lages, SC',
    'Balneário Camboriú, SC',
    'Brusque, SC',
    'Tubarão, SC',
    'Camboriú, SC',
    'São Bento do Sul, SC',
    'Navegantes, SC',
    'Caçador, SC',
    'Concórdia, SC',
    'Rio do Sul, SC',
    'Indaial, SC',
    'Gaspar, SC',
    'Biguaçu, SC',
    'Araranguá, SC',
    'Itapema, SC',
    'Içara, SC',
    'Mafra, SC',
    'São Francisco do Sul, SC',
    'Canoinhas, SC',
    'Videira, SC',
    'Xanxerê, SC',
    'Guaramirim, SC',
    'Laguna, SC',
    'Imbituba, SC',
    'Timbó, SC',
    'Rio Negrinho, SC',
    'São Miguel do Oeste, SC',
    'Araquari, SC',
    'Curitibanos, SC',
    'Tijucas, SC',
    'São João Batista, SC',
    'Campos Novos, SC',
    'Fraiburgo, SC',
    'Porto União, SC',
    'Pomerode, SC',
    'Braço do Norte, SC',
    'Penha, SC',
    'Sombrio, SC',
    'Joaçaba, SC',
    'Barra Velha, SC',
    'Xaxim, SC',
    'Forquilhinha, SC',
    'São Joaquim, SC',
    'Maravilha, SC',
    'Ituporanga, SC',
    'Capivari de Baixo, SC',
    'Guabiruba, SC',
    'São Lourenço do Oeste, SC',
    'Balneário Piçarras, SC',
    'Garopaba, SC',
    'Santo Amaro da Imperatriz, SC',
    'Capinzal, SC',
    'Orleans, SC',
    'Herval dOeste, SC',
    'Schroeder, SC',
    'Porto Belo, SC',
    'Itaiópolis, SC',
    'Itapoá, SC',
    'Urussanga, SC',
    'Pinhalzinho, SC',
    'Bombinhas, SC',
    'Jaguaruna, SC',
    'Papanduva, SC',
    'Três Barras, SC',
    'Ibirama, SC',
    'Otacílio Costa, SC',
    'Garuva, SC',
    'Taió, SC',
    'Morro da Fumaça, SC',
    'Abelardo Luz, SC',
    'Presidente Getúlio, SC',
    'Pouso Redondo, SC',
    'Seara, SC',
    'Massaranduba, SC',
    'Itapiranga, SC',
    'Santa Cecília, SC',
    'Cocal do Sul, SC',
    'Corupá, SC',
    'Palmitos, SC',
    'Dionísio Cerqueira, SC',
    'Nova Veneza, SC',
    'Lauro Müller, SC',
    'Nova Trento, SC',
    'Governador Celso Ramos, SC',
    'Ilhota, SC',
    'Siderópolis, SC',
    'São Ludgero, SC',
    'São José do Cedro, SC',
    'Balneário Arroio do Silva, SC',
    'Luiz Alves, SC',
    'Balneário Rincão, SC',
    'Sangão, SC',
    'Turvo, SC',
    'Canelinha, SC',
    'Lontras, SC',
    'Correia Pinto, SC',
    'Lebon Régis, SC',
    'Mondaí, SC',
    'Campo Alegre, SC',
    'Rio dos Cedros, SC',
    'Benedito Novo, SC',
    'Ponte Serrada, SC',
    'Gravatal, SC',
    'Rodeio, SC',
    'Balneário Gaivota, SC',
    'São Carlos, SC',
    'Irineópolis, SC',
    'Urubici, SC',
    'Balneário Barra do Sul, SC',
    'Agrolândia, SC',
    'Cunha Porã, SC',
    'Catanduvas, SC',
    'Apiúna, SC',
    'Faxinal dos Guedes, SC',
    'Irani, SC',
    'Jacinto Machado, SC',
    'Pescaria Brava, SC',
    'Bom Retiro, SC',
    'Alfredo Wagner, SC',
    'Porto Alegre, RS',
    'Caxias do Sul, RS',
    'Canoas, RS',
    'Pelotas, RS',
    'Gravataí, RS',
    'Santa Maria, RS',
    'Viamão, RS',
    'Novo Hamburgo, RS',
    'São Leopoldo, RS',
    'Rio Grande, RS',
    'Alvorada, RS',
    'Passo Fundo, RS',
    'Sapucaia do Sul, RS',
    'Santa Cruz do Sul, RS',
    'Cachoeirinha, RS',
    'Uruguaiana, RS',
    'Bento Gonçalves, RS',
    'Bagé, RS',
    'Erechim, RS',
    'Guaíba, RS',
    'Lajeado, RS',
    'Ijuí, RS',
    'Esteio, RS',
    'Cachoeira do Sul, RS',
    'Sapiranga, RS',
    'Santo Ângelo, RS',
    'SantAna do Livramento, RS',
    'Santa Rosa, RS',
    'Farroupilha, RS',
    'Alegrete, RS',
    'Venâncio Aires, RS',
    'Campo Bom, RS',
    'Vacaria, RS',
    'Camaquã, RS',
    'Montenegro, RS',
    'Carazinho, RS',
    'São Gabriel, RS',
    'São Borja, RS',
    'Cruz Alta, RS',
    'Parobé, RS',
    'Taquara, RS',
    'Canguçu, RS',
    'Capão da Canoa, RS',
    'Tramandaí, RS',
    'Estância Velha, RS',
    'Santiago, RS',
    'Osório, RS',
    'Canela, RS',
    'Marau, RS',
    'Panambi, RS',
    'São Lourenço do Sul, RS',
    'Santo Antônio da Patrulha, RS',
    'Eldorado do Sul, RS',
    'Charqueadas, RS',
    'Torres, RS',
    'Rosário do Sul, RS',
    'Rio Pardo, RS',
    'Dom Pedrito, RS',
    'Portão, RS',
    'Igrejinha, RS',
    'Itaqui, RS',
    'Gramado, RS',
    'Garibaldi, RS',
    'Estrela, RS',
    'Teutônia, RS',
    'Dois Irmãos, RS',
    'Caçapava do Sul, RS',
    'São Luiz Gonzaga, RS',
    'Palmeira das Missões, RS',
    'Frederico Westphalen, RS',
    'Candelária, RS',
    'Flores da Cunha, RS',
    'Soledade, RS',
    'Carlos Barbosa, RS',
    'Nova Santa Rita, RS',
    'Triunfo, RS',
    'Santa Vitória do Palmar, RS',
    'Três Coroas, RS',
    'Nova Prata, RS',
    'São José do Norte, RS',
    'Lagoa Vermelha, RS',
    'Vera Cruz, RS',
    'Taquari, RS',
    'Veranópolis, RS',
    'Jaguarão, RS',
    'Guaporé, RS',
    'São Sebastião do Caí, RS',
    'Encruzilhada do Sul, RS',
    'Capão do Leão, RS',
    'Ivoti, RS',
    'Sarandi, RS',
    'Tapejara, RS',
    'São Jerônimo, RS',
    'Tupanciretã, RS',
    'Três de Maio, RS',
    'Três Passos, RS',
    'Imbé, RS',
    'São Sepé, RS',
    'Encantado, RS',
    'Quaraí, RS',
    'Nova Hartz, RS',
    'São Francisco de Paula, RS',
    'São Marcos, RS',
    'Nova Petrópolis, RS',
    'Rolante, RS',
    'Arroio do Meio, RS',
    'Butiá, RS',
    'Piratini, RS',
    'Ibirubá, RS',
    'Horizontina, RS',
    'Júlio de Castilhos, RS',
    'Arroio Grande, RS',
    'São Francisco de Assis, RS',
    'Serafina Corrêa, RS',
    'Não-Me-Toque, RS',
    'Tapes, RS',
    'Xangri-lá, RS',
    'Cidreira, RS',
    'Sananduva, RS',
    'Agudo, RS',
    'Getúlio Vargas, RS',
    'São Pedro do Sul, RS',
    'Giruá, RS',
    'Restinga Sêca, RS',
    'Espumoso, RS',
    'Dom Feliciano, RS',
    'Sobradinho, RS',
    'Balneário Pinhal, RS',
    'Bom Princípio, RS',
    'Cerro Largo, RS',
    'Arroio dos Ratos, RS',
    'Santo Cristo, RS',
    'Santo Augusto, RS',
    'Feliz, RS',
    'Barra do Ribeiro, RS',
    'Arroio do Tigre, RS',
    'Tenente Portela, RS',
    'Crissiumal, RS',
    'Antônio Prado, RS',
    'Mostardas, RS',
    'Cerro Grande do Sul, RS',
    'Salto do Jacuí, RS',
    'Cruzeiro do Sul, RS',
    'Bom Retiro do Sul, RS',
    'Cacequi, RS',
    'Capela de Santana, RS',
    'Pinheiro Machado, RS',
    'Vale do Sol, RS',
    'Redentora, RS',
    'Nonoai, RS',
    'Roca Sales, RS',
    'Palmares do Sul, RS',
    'Terra de Areia, RS',
    'Bom Jesus, RS',
    'Três Cachoeiras, RS',
    'Barros Cassal, RS',
    'Jaguari, RS',
    'Seberi, RS',
    'Ronda Alta, RS',
    'Tapera, RS',
    'Arroio do Sal, RS',
    'Arvorezinha, RS',
    'Fontoura Xavier, RS',
    'Sinimbu, RS',
    'Porto Xavier, RS',
    'Nova Bassano, RS',
    'Boa Vista, RR',
    'Rorainópolis, RR',
    'Caracaraí, RR',
    'Pacaraima, RR',
    'Cantá, RR',
    'Mucajaí, RR',
    'Alto Alegre, RR',
    'Amajari, RR',
    'Bonfim, RR',
    'Iracema, RR',
    'Normandia, RR',
    'Uiramutã, RR',
    'Caroebe, RR',
    'Porto Velho, RO',
    'Ji-Paraná, RO',
    'Ariquemes, RO',
    'Vilhena, RO',
    'Cacoal, RO',
    'Rolim de Moura, RO',
    'Jaru, RO',
    'Guajará-Mirim, RO',
    'Machadinho DOeste, RO',
    'Buritis, RO',
    'Pimenta Bueno, RO',
    'Ouro Preto do Oeste, RO',
    'Espigão DOeste, RO',
    'Nova Mamoré, RO',
    'Candeias do Jamari, RO',
    'Cujubim, RO',
    'São Miguel do Guaporé, RO',
    'Alta Floresta DOeste, RO',
    'Alto Paraíso, RO',
    'São Francisco do Guaporé, RO',
    'Nova Brasilândia DOeste, RO',
    'Costa Marques, RO',
    'Presidente Médici, RO',
    'Monte Negro, RO',
    'Cerejeiras, RO',
    'Colorado do Oeste, RO',
    'Campo Novo de Rondônia, RO',
    'Alvorada DOeste, RO',
    'Alto Alegre dos Parecis, RO',
    'Seringueiras, RO',
    'Chupinguaia, RO',
    'Vale do Anari, RO',
    'Urupá, RO',
    'Itapuã do Oeste, RO',
    'Mirante da Serra, RO',
    'Theobroma, RO',
    'Natal, RN',
    'Mossoró, RN',
    'Parnamirim, RN',
    'São Gonçalo do Amarante, RN',
    'Macaíba, RN',
    'Ceará-Mirim, RN',
    'Caicó, RN',
    'Açu, RN',
    'Currais Novos, RN',
    'São José de Mipibu, RN',
    'Santa Cruz, RN',
    'Nova Cruz, RN',
    'Apodi, RN',
    'João Câmara, RN',
    'Canguaretama, RN',
    'Touros, RN',
    'Macau, RN',
    'Pau dos Ferros, RN',
    'Extremoz, RN',
    'Baraúna, RN',
    'Nísia Floresta, RN',
    'Areia Branca, RN',
    'Goianinha, RN',
    'Santo Antônio, RN',
    'São Miguel, RN',
    'Monte Alegre, RN',
    'Parelhas, RN',
    'Caraúbas, RN',
    'Jucurutu, RN',
    'São Paulo do Potengi, RN',
    'Guamaré, RN',
    'Tangará, RN',
    'Lagoa Nova, RN',
    'Ipanguaçu, RN',
    'Poço Branco, RN',
    'Pendências, RN',
    'Jardim de Piranhas, RN',
    'Upanema, RN',
    'Alto do Rodrigues, RN',
    'Pedro Velho, RN',
    'Tibau do Sul, RN',
    'Arês, RN',
    'Ielmo Marinho, RN',
    'Passa e Fica, RN',
    'Alexandria, RN',
    'Governador Dix-Sept Rosado, RN',
    'São José do Campestre, RN',
    'Brejinho, RN',
    'Patu, RN',
    'Vera Cruz, RN',
    'Maxaranguape, RN',
    'Jardim do Seridó, RN',
    'Taipu, RN',
    'Serra do Mel, RN',
    'Santana do Matos, RN',
    'Angicos, RN',
    'Lajes, RN',
    'Campo Redondo, RN',
    'Cerro Corá, RN',
    'Montanhas, RN',
    'Acari, RN',
    'São Tomé, RN',
    'Afonso Bezerra, RN',
    'Carnaubais, RN',
    'Rio do Fogo, RN',
    'Tenente Ananias, RN',
    'Serra Caiada, RN',
    'Grossos, RN',
    'Umarizal, RN',
    'Espírito Santo, RN',
    'São Miguel do Gostoso, RN',
    'Januário Cicco, RN',
    'Bom Jesus, RN',
    'Luís Gomes, RN',
    'Rio de Janeiro, RJ',
    'São Gonçalo, RJ',
    'Duque de Caxias, RJ',
    'Nova Iguaçu, RJ',
    'Niterói, RJ',
    'Belford Roxo, RJ',
    'Campos dos Goytacazes, RJ',
    'São João de Meriti, RJ',
    'Petrópolis, RJ',
    'Volta Redonda, RJ',
    'Macaé, RJ',
    'Magé, RJ',
    'Itaboraí, RJ',
    'Cabo Frio, RJ',
    'Angra dos Reis, RJ',
    'Nova Friburgo, RJ',
    'Teresópolis, RJ',
    'Barra Mansa, RJ',
    'Mesquita, RJ',
    'Maricá, RJ',
    'Nilópolis, RJ',
    'Rio das Ostras, RJ',
    'Queimados, RJ',
    'Itaguaí, RJ',
    'Araruama, RJ',
    'Resende, RJ',
    'São Pedro da Aldeia, RJ',
    'Japeri, RJ',
    'Itaperuna, RJ',
    'Barra do Piraí, RJ',
    'Saquarema, RJ',
    'Seropédica, RJ',
    'Três Rios, RJ',
    'Valença, RJ',
    'Guapimirim, RJ',
    'Rio Bonito, RJ',
    'Cachoeiras de Macacu, RJ',
    'Paracambi, RJ',
    'Mangaratiba, RJ',
    'Casimiro de Abreu, RJ',
    'Paraíba do Sul, RJ',
    'Paraty, RJ',
    'Santo Antônio de Pádua, RJ',
    'São Francisco de Itabapoana, RJ',
    'São Fidélis, RJ',
    'Bom Jesus do Itabapoana, RJ',
    'Vassouras, RJ',
    'São João da Barra, RJ',
    'Armação dos Búzios, RJ',
    'Tanguá, RJ',
    'Itatiaia, RJ',
    'Arraial do Cabo, RJ',
    'Piraí, RJ',
    'Iguaba Grande, RJ',
    'Paty do Alferes, RJ',
    'Bom Jardim, RJ',
    'Miracema, RJ',
    'Miguel Pereira, RJ',
    'Pinheiral, RJ',
    'Quissamã, RJ',
    'Conceição de Macabu, RJ',
    'Itaocara, RJ',
    'Cordeiro, RJ',
    'São José do Vale do Rio Preto, RJ',
    'Silva Jardim, RJ',
    'Porto Real, RJ',
    'Cantagalo, RJ',
    'Carmo, RJ',
    'Porciúncula, RJ',
    'Mendes, RJ',
    'Rio Claro, RJ',
    'Sapucaia, RJ',
    'Carapebus, RJ',
    'Sumidouro, RJ',
    'Cambuci, RJ',
    'Italva, RJ',
    'Natividade, RJ',
    'Quatis, RJ',
    'Engenheiro Paulo de Frontin, RJ',
    'Cardoso Moreira, RJ',
    'Areal, RJ',
    'Aperibé, RJ',
    'Duas Barras, RJ',
    'Varre-Sai, RJ',
    'Trajano de Moraes, RJ',
    'Santa Maria Madalena, RJ',
    'Curitiba, PR',
    'Londrina, PR',
    'Maringá, PR',
    'Ponta Grossa, PR',
    'Cascavel, PR',
    'São José dos Pinhais, PR',
    'Foz do Iguaçu, PR',
    'Colombo, PR',
    'Guarapuava, PR',
    'Paranaguá, PR',
    'Araucária, PR',
    'Toledo, PR',
    'Apucarana, PR',
    'Campo Largo, PR',
    'Pinhais, PR',
    'Arapongas, PR',
    'Almirante Tamandaré, PR',
    'Piraquara, PR',
    'Umuarama, PR',
    'Cambé, PR',
    'Fazenda Rio Grande, PR',
    'Sarandi, PR',
    'Campo Mourão, PR',
    'Francisco Beltrão, PR',
    'Paranavaí, PR',
    'Cianorte, PR',
    'Pato Branco, PR',
    'Telêmaco Borba, PR',
    'Castro, PR',
    'Rolândia, PR',
    'Irati, PR',
    'União da Vitória, PR',
    'Ibiporã, PR',
    'Marechal Cândido Rondon, PR',
    'Prudentópolis, PR',
    'Palmas, PR',
    'Lapa, PR',
    'Cornélio Procópio, PR',
    'São Mateus do Sul, PR',
    'Medianeira, PR',
    'Santo Antônio da Platina, PR',
    'Campina Grande do Sul, PR',
    'Paiçandu, PR',
    'Dois Vizinhos, PR',
    'Jacarezinho, PR',
    'Guaratuba, PR',
    'Marialva, PR',
    'Matinhos, PR',
    'Jaguariaíva, PR',
    'Quedas do Iguaçu, PR',
    'Rio Negro, PR',
    'Mandaguari, PR',
    'Palmeira, PR',
    'Guaíra, PR',
    'Assis Chateaubriand, PR',
    'Imbituva, PR',
    'Pinhão, PR',
    'Rio Branco do Sul, PR',
    'Palotina, PR',
    'Laranjeiras do Sul, PR',
    'Ivaiporã, PR',
    'Ibaiti, PR',
    'Bandeirantes, PR',
    'Campo Magro, PR',
    'Pitanga, PR',
    'Itaperuçu, PR',
    'Goioerê, PR',
    'Pontal do Paraná, PR',
    'Arapoti, PR',
    'Nova Esperança, PR',
    'Mandirituba, PR',
    'São Miguel do Iguaçu, PR',
    'Santa Helena, PR',
    'Reserva, PR',
    'Astorga, PR',
    'Piraí do Sul, PR',
    'Cambará, PR',
    'Colorado, PR',
    'Quatro Barras, PR',
    'Carambeí, PR',
    'Santa Terezinha de Itaipu, PR',
    'Loanda, PR',
    'Mandaguaçu, PR',
    'Altônia, PR',
    'Ortigueira, PR',
    'Siqueira Campos, PR',
    'Jandaia do Sul, PR',
    'Cruzeiro do Oeste, PR',
    'Ubiratã, PR',
    'Tibagi, PR',
    'Coronel Vivida, PR',
    'Santo Antônio do Sudoeste, PR',
    'Andirá, PR',
    'Ampére, PR',
    'Sengés, PR',
    'Quitandinha, PR',
    'Wenceslau Braz, PR',
    'Capanema, PR',
    'Chopinzinho, PR',
    'Contenda, PR',
    'Antonina, PR',
    'Cafelândia, PR',
    'Cruz Machado, PR',
    'Matelândia, PR',
    'Cerro Azul, PR',
    'Terra Roxa, PR',
    'Faxinal, PR',
    'Terra Boa, PR',
    'Tijucas do Sul, PR',
    'Corbélia, PR',
    'Terra Rica, PR',
    'Realeza, PR',
    'Mangueirinha, PR',
    'Morretes, PR',
    'Tapejara, PR',
    'Sertanópolis, PR',
    'Bituruna, PR',
    'Clevelândia, PR',
    'Candói, PR',
    'Capitão Leônidas Marques, PR',
    'Rio Azul, PR',
    'Bela Vista do Paraíso, PR',
    'São João do Triunfo, PR',
    'Ipiranga, PR',
    'Curiúva, PR',
    'Tamarana, PR',
    'Rebouças, PR',
    'Salto do Lontra, PR',
    'Alto Paraná, PR',
    'Santa Izabel do Oeste, PR',
    'Assaí, PR',
    'Cândido de Abreu, PR',
    'Marmeleiro, PR',
    'Carlópolis, PR',
    'Paraíso do Norte, PR',
    'Ivaí, PR',
    'Araruna, PR',
    'Peabiru, PR',
    'Engenheiro Beltrão, PR',
    'Campina da Lagoa, PR',
    'Jaguapitã, PR',
    'Mallet, PR',
    'General Carneiro, PR',
    'Iporã, PR',
    'Manoel Ribas, PR',
    'Imbaú, PR',
    'Planalto, PR',
    'Cantagalo, PR',
    'Bocaiúva do Sul, PR',
    'Rio Bonito do Iguaçu, PR',
    'Balsa Nova, PR',
    'Nova Londrina, PR',
    'Piên, PR',
    'Turvo, PR',
    'Cidade Gaúcha, PR',
    'Mamborê, PR',
    'Ribeirão do Pinhal, PR',
    'Teixeira Soares, PR',
    'Palmital, PR',
    'Jataizinho, PR',
    'Porecatu, PR',
    'Santa Fé, PR',
    'Ventania, PR',
    'Querência do Norte, PR',
    'Itapejara dOeste, PR',
    'Joaquim Távora, PR',
    'Três Barras do Paraná, PR',
    'Guaraniaçu, PR',
    'Moreira Sales, PR',
    'Céu Azul, PR',
    'Paranacity, PR',
    'Alvorada do Sul, PR',
    'Itaipulândia, PR',
    'Santa Mariana, PR',
    'Nova Laranjeiras, PR',
    'Pérola, PR',
    'Barbosa Ferraz, PR',
    'Uraí, PR',
    'Primeiro de Maio, PR',
    'Inácio Martins, PR',
    'São Pedro do Ivaí, PR',
    'São Jerônimo da Serra, PR',
    'Jardim Alegre, PR',
    'Mauá da Serra, PR',
    'Missal, PR',
    'Centenário do Sul, PR',
    'Ribeirão Claro, PR',
    'Nova Prata do Iguaçu, PR',
    'Florestópolis, PR',
    'Barracão, PR',
    'Mariluz, PR',
    'Catanduvas, PR',
    'Nova Aurora, PR',
    'São João, PR',
    'Santa Tereza do Oeste, PR',
    'Iretama, PR',
    'Teresina, PI',
    'Parnaíba, PI',
    'Picos, PI',
    'Piripiri, PI',
    'Floriano, PI',
    'Barras, PI',
    'Campo Maior, PI',
    'União, PI',
    'Altos, PI',
    'Esperantina, PI',
    'José de Freitas, PI',
    'Pedro II, PI',
    'Oeiras, PI',
    'São Raimundo Nonato, PI',
    'Miguel Alves, PI',
    'Luís Correia, PI',
    'Piracuruca, PI',
    'Cocal, PI',
    'Batalha, PI',
    'Corrente, PI',
    'Bom Jesus, PI',
    'Luzilândia, PI',
    'Uruçuí, PI',
    'Canto do Buriti, PI',
    'Valença do Piauí, PI',
    'São João do Piauí, PI',
    'Paulistana, PI',
    'Buriti dos Lopes, PI',
    'Castelo do Piauí, PI',
    'Jaicós, PI',
    'Pio IX, PI',
    'Regeneração, PI',
    'São Miguel do Tapuio, PI',
    'Amarante, PI',
    'Água Branca, PI',
    'Inhuma, PI',
    'Simões, PI',
    'Palmeirais, PI',
    'Elesbão Veloso, PI',
    'Joaquim Pires, PI',
    'Alto Longá, PI',
    'São Pedro do Piauí, PI',
    'Demerval Lobão, PI',
    'Simplício Mendes, PI',
    'Porto, PI',
    'Pimenteiras, PI',
    'Baixa Grande do Ribeiro, PI',
    'Fronteiras, PI',
    'Itainópolis, PI',
    'Capitão de Campos, PI',
    'Curimatá, PI',
    'Avelino Lopes, PI',
    'Itaueira, PI',
    'Caracol, PI',
    'Matias Olímpio, PI',
    'Parnaguá, PI',
    'Gilbués, PI',
    'Cabeceiras do Piauí, PI',
    'Monte Alegre do Piauí, PI',
    'Monsenhor Gil, PI',
    'Guadalupe, PI',
    'Beneditinos, PI',
    'Cristino Castro, PI',
    'Sigefredo Pacheco, PI',
    'Ferreiros, PE',
    'Recife, PE',
    'Jaboatão dos Guararapes, PE',
    'Olinda, PE',
    'Caruaru, PE',
    'Petrolina, PE',
    'Paulista, PE',
    'Cabo de Santo Agostinho, PE',
    'Camaragibe, PE',
    'Garanhuns, PE',
    'Vitória de Santo Antão, PE',
    'Igarassu, PE',
    'São Lourenço da Mata, PE',
    'Santa Cruz do Capibaribe, PE',
    'Abreu e Lima, PE',
    'Ipojuca, PE',
    'Serra Talhada, PE',
    'Gravatá, PE',
    'Araripina, PE',
    'Carpina, PE',
    'Goiana, PE',
    'Belo Jardim, PE',
    'Arcoverde, PE',
    'Ouricuri, PE',
    'Escada, PE',
    'Pesqueira, PE',
    'Surubim, PE',
    'Moreno, PE',
    'Palmares, PE',
    'Salgueiro, PE',
    'Bezerros, PE',
    'São Bento do Una, PE',
    'Buíque, PE',
    'Paudalho, PE',
    'Limoeiro, PE',
    'Timbaúba, PE',
    'Brejo da Madre de Deus, PE',
    'Bom Conselho, PE',
    'Ribeirão, PE',
    'Toritama, PE',
    'Sirinhaém, PE',
    'Águas Belas, PE',
    'Catende, PE',
    'Barreiros, PE',
    'Santa Maria da Boa Vista, PE',
    'Lajedo, PE',
    'Bom Jardim, PE',
    'Bodocó, PE',
    'Aliança, PE',
    'Bonito, PE',
    'Custódia, PE',
    'Afogados da Ingazeira, PE',
    'São Caitano, PE',
    'Água Preta, PE',
    'Petrolândia, PE',
    'Itambé, PE',
    'Sertânia, PE',
    'Cabrobó, PE',
    'São José do Egito, PE',
    'São José do Belmonte, PE',
    'João Alfredo, PE',
    'Floresta, PE',
    'Vicência, PE',
    'Nazaré da Mata, PE',
    'Exu, PE',
    'Gameleira, PE',
    'Ipubi, PE',
    'Trindade, PE',
    'Glória do Goitá, PE',
    'Ibimirim, PE',
    'Taquaritinga do Norte, PE',
    'Caetés, PE',
    'Tabira, PE',
    'Passira, PE',
    'Tupanatinga, PE',
    'Sanharó, PE',
    'Pombos, PE',
    'Itapissuma, PE',
    'Ilha de Itamaracá, PE',
    'Condado, PE',
    'Tacaratu, PE',
    'Panelas, PE',
    'Quipapá, PE',
    'Itaíba, PE',
    'Lagoa Grande, PE',
    'Macaparana, PE',
    'Agrestina, PE',
    'Canhotinho, PE',
    'Cupira, PE',
    'Inajá, PE',
    'Orobó, PE',
    'Tamandaré, PE',
    'Rio Formoso, PE',
    'São João, PE',
    'Altinho, PE',
    'Amaraji, PE',
    'Pedra, PE',
    'Flores, PE',
    'Feira Nova, PE',
    'Parnamirim, PE',
    'Manari, PE',
    'Chã Grande, PE',
    'São José da Coroa Grande, PE',
    'Lagoa de Itaenga, PE',
    'São Joaquim do Monte, PE',
    'Vertentes, PE',
    'Araçoiaba, PE',
    'Riacho das Almas, PE',
    'Belém do São Francisco, PE',
    'Cachoeirinha, PE',
    'Capoeiras, PE',
    'Afrânio, PE',
    'Carnaíba, PE',
    'Iati, PE',
    'Dormentes, PE',
    'Serrita, PE',
    'Camocim de São Félix, PE',
    'Venturosa, PE',
    'Lagoa do Carro, PE',
    'Correntes, PE',
    'São Vicente Férrer, PE',
    'Jataúba, PE',
    'Itaquitinga, PE',
    'Machados, PE',
    'Lagoa dos Gatos, PE',
    'São Benedito do Sul, PE',
    'Joaquim Nabuco, PE',
    'Saloá, PE',
    'Santa Cruz, PE',
    'Frei Miguelinho, PE',
    'Mirandiba, PE',
    'Jurema, PE',
    'Orocó, PE',
    'Triunfo, PE',
    'Primavera, PE',
    'Jupi, PE',
    'Jatobá, PE',
    'Alagoinha, PE',
    'Xexéu, PE',
    'Santa Filomena, PE',
    'Barra de Guabiraba, PE',
    'Casinhas, PE',
    'Santa Maria do Cambucá, PE',
    'Tracunhaém, PE',
    'Chã de Alegria, PE',
    'Itapetim, PE',
    'Lagoa do Ouro, PE',
    'Buenos Aires, PE',
    'Carnaubeira da Penha, PE',
    'Tacaimbó, PE',
    'Betânia, PE',
    'Santa Cruz da Baixa Verde, PE',
    'Cortês, PE',
    'Iguaracy, PE',
    'Belém de Maria, PE',
    'Cedro, PE',
    'Santa Terezinha, PE',
    'Jaqueira, PE',
    'Paranatama, PE',
    'Jucati, PE',
    'Poção, PE',
    'Angelim, PE',
    'Moreilândia, PE',
    'Salgadinho, PE',
    'Maraial, PE',
    'Calçado, PE',
    'Terra Nova, PE',
    'João Pessoa, PB',
    'Campina Grande, PB',
    'Santa Rita, PB',
    'Patos, PB',
    'Bayeux, PB',
    'Sousa, PB',
    'Cabedelo, PB',
    'Cajazeiras, PB',
    'Guarabira, PB',
    'Sapé, PB',
    'Mamanguape, PB',
    'Queimadas, PB',
    'São Bento, PB',
    'Monteiro, PB',
    'Esperança, PB',
    'Pombal, PB',
    'Catolé do Rocha, PB',
    'Pedras de Fogo, PB',
    'Alagoa Grande, PB',
    'Lagoa Seca, PB',
    'Solânea, PB',
    'Conde, PB',
    'Itaporanga, PB',
    'Itabaiana, PB',
    'Rio Tinto, PB',
    'Princesa Isabel, PB',
    'Areia, PB',
    'Caaporã, PB',
    'Mari, PB',
    'Bananeiras, PB',
    'Alagoa Nova, PB',
    'Araruna, PB',
    'São José de Piranhas, PB',
    'Cuité, PB',
    'Remígio, PB',
    'Alhandra, PB',
    'Pitimbu, PB',
    'Aroeiras, PB',
    'Conceição, PB',
    'Itapororoca, PB',
    'Pocinhos, PB',
    'Picuí, PB',
    'Juazeirinho, PB',
    'Ingá, PB',
    'São João do Rio do Peixe, PB',
    'Boqueirão, PB',
    'Belém, PB',
    'Cruz do Espírito Santo, PB',
    'Cacimba de Dentro, PB',
    'Sumé, PB',
    'Araçagi, PB',
    'Piancó, PB',
    'Barra de Santa Rosa, PB',
    'Taperoá, PB',
    'Santa Luzia, PB',
    'Coremas, PB',
    'Uiraúna, PB',
    'Teixeira, PB',
    'Soledade, PB',
    'Tavares, PB',
    'Alagoinha, PB',
    'Jacaraú, PB',
    'Brejo do Cruz, PB',
    'Gurinhém, PB',
    'Massaranduba, PB',
    'Serra Branca, PB',
    'Puxinanã, PB',
    'Arara, PB',
    'Lucena, PB',
    'Mogeiro, PB',
    'Paulista, PB',
    'Bonito de Santa Fé, PB',
    'Salgado de São Félix, PB',
    'Pilar, PB',
    'Imaculada, PB',
    'São Sebastião de Lagoa de Roça, PB',
    'Fagundes, PB',
    'Itatuba, PB',
    'Tacima, PB',
    'Manaíra, PB',
    'São Vicente do Seridó, PB',
    'Juripiranga, PB',
    'Nova Floresta, PB',
    'Pirpirituba, PB',
    'Natuba, PB',
    'Água Branca, PB',
    'Dona Inês, PB',
    'Cachoeira dos Índios, PB',
    'Jacareacanga, PA',
    'Belém, PA',
    'Ananindeua, PA',
    'Santarém, PA',
    'Marabá, PA',
    'Parauapebas, PA',
    'Castanhal, PA',
    'Abaetetuba, PA',
    'Cametá, PA',
    'Marituba, PA',
    'São Félix do Xingu, PA',
    'Bragança, PA',
    'Barcarena, PA',
    'Altamira, PA',
    'Tucuruí, PA',
    'Paragominas, PA',
    'Tailândia, PA',
    'Breves, PA',
    'Itaituba, PA',
    'Redenção, PA',
    'Moju, PA',
    'Novo Repartimento, PA',
    'Santana do Araguaia, PA',
    'Oriximiná, PA',
    'Santa Izabel do Pará, PA',
    'Capanema, PA',
    'Breu Branco, PA',
    'Ipixuna do Pará, PA',
    'Benevides, PA',
    'Tomé-Açu, PA',
    'Portel, PA',
    'Igarapé-Miri, PA',
    'Ulianópolis, PA',
    'Viseu, PA',
    'Dom Eliseu, PA',
    'Jacundá, PA',
    'São Miguel do Guamá, PA',
    'Juruti, PA',
    'Monte Alegre, PA',
    'Alenquer, PA',
    'Acará, PA',
    'Vigia, PA',
    'Capitão Poço, PA',
    'Itupiranga, PA',
    'Rondon do Pará, PA',
    'Óbidos, PA',
    'Rurópolis, PA',
    'Baião, PA',
    'Pacajá, PA',
    'Conceição do Araguaia, PA',
    'Augusto Corrêa, PA',
    'Xinguara, PA',
    'Uruará, PA',
    'Porto de Moz, PA',
    'Goianésia do Pará, PA',
    'Muaná, PA',
    'Salinópolis, PA',
    'Curuçá, PA',
    'Tucumã, PA',
    'Afuá, PA',
    'Igarapé-Açu, PA',
    'Canaã dos Carajás, PA',
    'Curralinho, PA',
    'Cachoeira do Piriá, PA',
    'Concórdia do Pará, PA',
    'Gurupá, PA',
    'Eldorado do Carajás, PA',
    'Almeirim, PA',
    'Ourilândia do Norte, PA',
    'Oeiras do Pará, PA',
    'Irituia, PA',
    'Medicilândia, PA',
    'Santo Antônio do Tauá, PA',
    'Placas, PA',
    'São Domingos do Capim, PA',
    'Aurora do Pará, PA',
    'Ponta de Pedras, PA',
    'Bagre, PA',
    'Mocajuba, PA',
    'Tracuateua, PA',
    'Mãe do Rio, PA',
    'Anajás, PA',
    'Prainha, PA',
    'Bujaru, PA',
    'Limoeiro do Ajuru, PA',
    'Maracanã, PA',
    'Anapu, PA',
    'Marapanim, PA',
    'Melgaço, PA',
    'Água Azul do Norte, PA',
    'São Sebastião da Boa Vista, PA',
    'Garrafão do Norte, PA',
    'São Domingos do Araguaia, PA',
    'Novo Progresso, PA',
    'Soure, PA',
    'Santa Maria do Pará, PA',
    'São Geraldo do Araguaia, PA',
    'Salvaterra, PA',
    'Cachoeira do Arari, PA',
    'Chaves, PA',
    'São João de Pirabas, PA',
    'Santa Maria das Barreiras, PA',
    'Santa Bárbara do Pará, PA',
    'Nova Esperança do Piriá, PA',
    'Floresta do Araguaia, PA',
    'Santa Luzia do Pará, PA',
    'Trairão, PA',
    'Terra Santa, PA',
    'Rio Maria, PA',
    'São Caetano de Odivelas, PA',
    'Ourém, PA',
    'Belterra, PA',
    'Curionópolis, PA',
    'Bom Jesus do Tocantins, PA',
    'Nova Ipixuna, PA',
    'Bonito, PA',
    'Aveiro, PA',
    'Mojuí dos Campos, PA',
    'São Francisco do Pará, PA',
    'Nova Timboteua, PA',
    'Vitória do Xingu, PA',
    'Brasil Novo, PA',
    'Curuá, PA',
    'São João do Araguaia, PA',
    'Cumaru do Norte, PA',
    'Quatipuru, PA',
    'Piçarra, PA',
    'Colares, PA',
    'Inhangapi, PA',
    'Terra Alta, PA',
    'Senador José Porfírio, PA',
    'Primavera, PA',
    'Santa Cruz do Arari, PA',
    'Cuiabá, MT',
    'Várzea Grande, MT',
    'Rondonópolis, MT',
    'Sinop, MT',
    'Tangará da Serra, MT',
    'Cáceres, MT',
    'Sorriso, MT',
    'Lucas do Rio Verde, MT',
    'Primavera do Leste, MT',
    'Barra do Garças, MT',
    'Alta Floresta, MT',
    'Nova Mutum, MT',
    'Pontes e Lacerda, MT',
    'Campo Verde, MT',
    'Juína, MT',
    'Colniza, MT',
    'Campo Novo do Parecis, MT',
    'Guarantã do Norte, MT',
    'Peixoto de Azevedo, MT',
    'Barra do Bugres, MT',
    'Juara, MT',
    'Colíder, MT',
    'Poconé, MT',
    'Confresa, MT',
    'Mirassol dOeste, MT',
    'Jaciara, MT',
    'Sapezal, MT',
    'Vila Rica, MT',
    'Água Boa, MT',
    'Paranatinga, MT',
    'Aripuanã, MT',
    'Chapada dos Guimarães, MT',
    'Diamantino, MT',
    'Canarana, MT',
    'Nova Xavantina, MT',
    'São José do Rio Claro, MT',
    'Comodoro, MT',
    'Nova Olímpia, MT',
    'Cotriguaçu, MT',
    'Brasnorte, MT',
    'Alto Araguaia, MT',
    'São José dos Quatro Marcos, MT',
    'Querência, MT',
    'Pedra Preta, MT',
    'Santo Antônio do Leverger, MT',
    'Araputanga, MT',
    'Matupá, MT',
    'Rosário Oeste, MT',
    'Juruena, MT',
    'Vila Bela da Santíssima Trindade, MT',
    'Campinápolis, MT',
    'Nova Bandeirantes, MT',
    'Poxoréu, MT',
    'Guiratinga, MT',
    'Nobres, MT',
    'Feliz Natal, MT',
    'Tapurah, MT',
    'Itiquira, MT',
    'Nossa Senhora do Livramento, MT',
    'Nova Canaã do Norte, MT',
    'Porto Alegre do Norte, MT',
    'Nova Ubiratã, MT',
    'Cláudia, MT',
    'Alto Garças, MT',
    'Porto Esperidião, MT',
    'São Félix do Araguaia, MT',
    'Vera, MT',
    'Alto Paraguai, MT',
    'Alto Taquari, MT',
    'Paranaíta, MT',
    'Juscimeira, MT',
    'Ribeirão Cascalheira, MT',
    'Apiacás, MT',
    'Marcelândia, MT',
    'Carlinda, MT',
    'Campo Grande, MS',
    'Dourados, MS',
    'Três Lagoas, MS',
    'Corumbá, MS',
    'Ponta Porã, MS',
    'Sidrolândia, MS',
    'Naviraí, MS',
    'Nova Andradina, MS',
    'Maracaju, MS',
    'Aquidauana, MS',
    'Paranaíba, MS',
    'Amambai, MS',
    'Rio Brilhante, MS',
    'Coxim, MS',
    'Caarapó, MS',
    'Miranda, MS',
    'São Gabriel do Oeste, MS',
    'Chapadão do Sul, MS',
    'Aparecida do Taboado, MS',
    'Jardim, MS',
    'Itaporã, MS',
    'Anastácio, MS',
    'Ribas do Rio Pardo, MS',
    'Bela Vista, MS',
    'Ladário, MS',
    'Bataguassu, MS',
    'Ivinhema, MS',
    'Nova Alvorada do Sul, MS',
    'Terenos, MS',
    'Bonito, MS',
    'Cassilândia, MS',
    'Itaquiraí, MS',
    'Costa Rica, MS',
    'Sonora, MS',
    'Rio Verde de Mato Grosso, MS',
    'Fátima do Sul, MS',
    'Mundo Novo, MS',
    'Porto Murtinho, MS',
    'Iguatemi, MS',
    'Água Clara, MS',
    'Coronel Sapucaia, MS',
    'Paranhos, MS',
    'Nioaque, MS',
    'Camapuã, MS',
    'Deodápolis, MS',
    'Aral Moreira, MS',
    'Eldorado, MS',
    'Brasilândia, MS',
    'Tacuru, MS',
    'Dois Irmãos do Buriti, MS',
    'Batayporã, MS',
    'Angélica, MS',
    'Sete Quedas, MS',
    'Belo Horizonte, MG',
    'Uberlândia, MG',
    'Contagem, MG',
    'Juiz de Fora, MG',
    'Betim, MG',
    'Montes Claros, MG',
    'Ribeirão das Neves, MG',
    'Uberaba, MG',
    'Governador Valadares, MG',
    'Ipatinga, MG',
    'Sete Lagoas, MG',
    'Divinópolis, MG',
    'Santa Luzia, MG',
    'Ibirité, MG',
    'Poços de Caldas, MG',
    'Patos de Minas, MG',
    'Pouso Alegre, MG',
    'Teófilo Otoni, MG',
    'Barbacena, MG',
    'Sabará, MG',
    'Varginha, MG',
    'Vespasiano, MG',
    'Conselheiro Lafaiete, MG',
    'Itabira, MG',
    'Araguari, MG',
    'Ubá, MG',
    'Passos, MG',
    'Coronel Fabriciano, MG',
    'Muriaé, MG',
    'Araxá, MG',
    'Nova Serrana, MG',
    'Ituiutaba, MG',
    'Lavras, MG',
    'Itajubá, MG',
    'Nova Lima, MG',
    'Pará de Minas, MG',
    'Paracatu, MG',
    'Itaúna, MG',
    'Caratinga, MG',
    'Patrocínio, MG',
    'Manhuaçu, MG',
    'Timóteo, MG',
    'São João del Rei, MG',
    'Unaí, MG',
    'Curvelo, MG',
    'Alfenas, MG',
    'João Monlevade, MG',
    'Três Corações, MG',
    'Viçosa, MG',
    'Cataguases, MG',
    'Ouro Preto, MG',
    'Esmeraldas, MG',
    'Janaúba, MG',
    'São Sebastião do Paraíso, MG',
    'Januária, MG',
    'Formiga, MG',
    'Lagoa Santa, MG',
    'Pedro Leopoldo, MG',
    'Mariana, MG',
    'Frutal, MG',
    'Ponte Nova, MG',
    'Três Pontas, MG',
    'Pirapora, MG',
    'São Francisco, MG',
    'Congonhas, MG',
    'Campo Belo, MG',
    'Lagoa da Prata, MG',
    'Itabirito, MG',
    'Leopoldina, MG',
    'Guaxupé, MG',
    'Bom Despacho, MG',
    'Bocaiúva, MG',
    'Monte Carmelo, MG',
    'João Pinheiro, MG',
    'Diamantina, MG',
    'São Lourenço, MG',
    'Santos Dumont, MG',
    'Caeté, MG',
    'Igarapé, MG',
    'Santa Rita do Sapucaí, MG',
    'Visconde do Rio Branco, MG',
    'Machado, MG',
    'Almenara, MG',
    'Oliveira, MG',
    'Salinas, MG',
    'Andradas, MG',
    'Brumadinho, MG',
    'Arcos, MG',
    'Nanuque, MG',
    'Boa Esperança, MG',
    'Ouro Branco, MG',
    'Iturama, MG',
    'Várzea da Palma, MG',
    'Jaíba, MG',
    'Matozinhos, MG',
    'Capelinha, MG',
    'Porteirinha, MG',
    'Extrema, MG',
    'Araçuaí, MG',
    'São Gotardo, MG',
    'Santana do Paraíso, MG',
    'Além Paraíba, MG',
    'Piumhi, MG',
    'Itamarandiba, MG',
    'Guanhães, MG',
    'Taiobeiras, MG',
    'Sarzedo, MG',
    'Ouro Fino, MG',
    'Barão de Cocais, MG',
    'Três Marias, MG',
    'Carangola, MG',
    'São Joaquim de Bicas, MG',
    'Brasília de Minas, MG',
    'Pompéu, MG',
    'Santa Bárbara, MG',
    'Mateus Leme, MG',
    'Espinosa, MG',
    'Minas Novas, MG',
    'Novo Cruzeiro, MG',
    'Rio Pardo de Minas, MG',
    'Carmo do Paranaíba, MG',
    'Cambuí, MG',
    'Cláudio, MG',
    'Campos Gerais, MG',
    'Conceição das Alagoas, MG',
    'Santo Antônio do Monte, MG',
    'Elói Mendes, MG',
    'Pitangui, MG',
    'Buritizeiro, MG',
    'Prata, MG',
    'Coromandel, MG',
    'Juatuba, MG',
    'Mantena, MG',
    'Belo Oriente, MG',
    'Mutum, MG',
    'Nepomuceno, MG',
    'Coração de Jesus, MG',
    'Sacramento, MG',
    'Jacutinga, MG',
    'São João Nepomuceno, MG',
    'Francisco Sá, MG',
    'Carandaí, MG',
    'São Gonçalo do Sapucaí, MG',
    'Jequitinhonha, MG',
    'Ibiá, MG',
    'Tupaciguara, MG',
    'Espera Feliz, MG',
    'Buritis, MG',
    'Aimorés, MG',
    'São João da Ponte, MG',
    'Paraopeba, MG',
    'São José da Lapa, MG',
    'Pedra Azul, MG',
    'Monte Sião, MG',
    'Inhapim, MG',
    'Bambuí, MG',
    'Caraí, MG',
    'São João do Paraíso, MG',
    'Raul Soares, MG',
    'Corinto, MG',
    'Abaeté, MG',
    'Itambacuri, MG',
    'Conselheiro Pena, MG',
    'Carmo do Cajuru, MG',
    'Manhumirim, MG',
    'Camanducaia, MG',
    'Itapecerica, MG',
    'Paraguaçu, MG',
    'Perdões, MG',
    'Caxambu, MG',
    'Monte Santo de Minas, MG',
    'Paraisópolis, MG',
    'Monte Alegre de Minas, MG',
    'Carmo do Rio Claro, MG',
    'Campestre, MG',
    'Itaobim, MG',
    'Lambari, MG',
    'Barroso, MG',
    'Serro, MG',
    'Medina, MG',
    'Vazante, MG',
    'Jaboticatubas, MG',
    'Monte Azul, MG',
    'Muzambinho, MG',
    'Padre Paraíso, MG',
    'Turmalina, MG',
    'Ipanema, MG',
    'Alpinópolis, MG',
    'Divino, MG',
    'Santa Vitória, MG',
    'Lajinha, MG',
    'Simonésia, MG',
    'Borda da Mata, MG',
    'Campina Verde, MG',
    'Carmópolis de Minas, MG',
    'Presidente Olegário, MG',
    'Varzelândia, MG',
    'Águas Formosas, MG',
    'Baependi, MG',
    'Matipó, MG',
    'Ervália, MG',
    'Guaranésia, MG',
    'Ipaba, MG',
    'Fronteira, MG',
    'Santo Antônio do Amparo, MG',
    'Malacacheta, MG',
    'Carlos Chagas, MG',
    'Luz, MG',
    'Ladainha, MG',
    'Itacarambi, MG',
    'Lagoa Formosa, MG',
    'Manga, MG',
    'Rio Pomba, MG',
    'Arinos, MG',
    'Cássia, MG',
    'Piranga, MG',
    'Bom Sucesso, MG',
    'Peçanha, MG',
    'Nova Era, MG',
    'Urucuia, MG',
    'Conceição do Mato Dentro, MG',
    'Resplendor, MG',
    'São Domingos do Prata, MG',
    'Brasilândia de Minas, MG',
    'Nova Resende, MG',
    'Poço Fundo, MG',
    'Campanha, MG',
    'Tocantins, MG',
    'Lima Duarte, MG',
    'Poté, MG',
    'Raposos, MG',
    'Perdizes, MG',
    'Passa Quatro, MG',
    'Santa Margarida, MG',
    'Capinópolis, MG',
    'Itaú de Minas, MG',
    'Nova Ponte, MG',
    'Grão Mogol, MG',
    'Papagaios, MG',
    'Itamonte, MG',
    'Mário Campos, MG',
    'São João Evangelista, MG',
    'Campos Altos, MG',
    'Cruzília, MG',
    'Felixlândia, MG',
    'Itanhandu, MG',
    'Itapagipe, MG',
    'Joaíma, MG',
    'Entre Rios de Minas, MG',
    'Capitão Enéas, MG',
    'Sabinópolis, MG',
    'Chapada do Norte, MG',
    'Areado, MG',
    'Miraí, MG',
    'Alvinópolis, MG',
    'Itinga, MG',
    'Carmo de Minas, MG',
    'Botelhos, MG',
    'Candeias, MG',
    'Bom Jesus do Galho, MG',
    'Matias Barbosa, MG',
    'Montalvânia, MG',
    'Bicas, MG',
    'Santa Maria do Suaçuí, MG',
    'Caldas, MG',
    'Alterosa, MG',
    'Santa Juliana, MG',
    'Brazópolis, MG',
    'Astolfo Dutra, MG',
    'Rio Piracicaba, MG',
    'Tarumirim, MG',
    'Guapé, MG',
    'Chapada Gaúcha, MG',
    'Ibiraci, MG',
    'Cabo Verde, MG',
    'Maria da Fé, MG',
    'Conceição do Rio Verde, MG',
    'Virgem da Lapa, MG',
    'Águas Vermelhas, MG',
    'Mirabela, MG',
    'Itaguara, MG',
    'Martinho Campos, MG',
    'Abre Campo, MG',
    'Rio Casca, MG',
    'Dores do Indaiá, MG',
    'Água Boa, MG',
    'São João das Missões, MG',
    'Monte Belo, MG',
    'Lagoa Dourada, MG',
    'Cristais, MG',
    'Mar de Espanha, MG',
    'Itaipé, MG',
    'Cambuquira, MG',
    'São Gonçalo do Pará, MG',
    'São Geraldo, MG',
    'São Romão, MG',
    'Ubaí, MG',
    'Rio Vermelho, MG',
    'Ubaporanga, MG',
    'Ilicínea, MG',
    'Ataléia, MG',
    'Setubinha, MG',
    'Planura, MG',
    'Mato Verde, MG',
    'Rio Paranaíba, MG',
    'Jacinto, MG',
    'Pedras de Maria da Cruz, MG',
    'Itanhomi, MG',
    'Canápolis, MG',
    'Jequeri, MG',
    'Ponto dos Volantes, MG',
    'Congonhal, MG',
    'Icaraí de Minas, MG',
    'Carmo da Cachoeira, MG',
    'Andrelândia, MG',
    'Perdigão, MG',
    'Caetanópolis, MG',
    'Conceição dos Ouros, MG',
    'Berilo, MG',
    'Gouveia, MG',
    'São João do Manhuaçu, MG',
    'Serra do Salitre, MG',
    'Teixeiras, MG',
    'Campo do Meio, MG',
    'Itabirinha, MG',
    'Cachoeira de Minas, MG',
    'Resende Costa, MG',
    'Santo Antônio do Jacinto, MG',
    'Carmo da Mata, MG',
    'Bonito de Minas, MG',
    'Antônio Carlos, MG',
    'Estiva, MG',
    'Porto Firme, MG',
    'Divisópolis, MG',
    'Eugenópolis, MG',
    'Matias Cardoso, MG',
    'Itatiaiuçu, MG',
    'Engenheiro Caldas, MG',
    'Igaratinga, MG',
    'São Gonçalo do Rio Abaixo, MG',
    'Fervedouro, MG',
    'Pedralva, MG',
    'Iapu, MG',
    'Delta, MG',
    'Arceburgo, MG',
    'Bueno Brandão, MG',
    'São Tiago, MG',
    'Prudente de Morais, MG',
    'Jordânia, MG',
    'Santa Maria de Itabira, MG',
    'Miradouro, MG',
    'Novo Oriente de Minas, MG',
    'Juruaia, MG',
    'Pirapetinga, MG',
    'Mercês, MG',
    'Piraúba, MG',
    'Alto Rio Doce, MG',
    'Bom Repouso, MG',
    'Rio Acima, MG',
    'Recreio, MG',
    'Senhora dos Remédios, MG',
    'Virginópolis, MG',
    'Ninheira, MG',
    'Conceição da Aparecida, MG',
    'Centralina, MG',
    'Buenópolis, MG',
    'Urucânia, MG',
    'Francisco Badaró, MG',
    'Guaraciaba, MG',
    'Dores de Campos, MG',
    'Bela Vista de Minas, MG',
    'Rubim, MG',
    'Cristina, MG',
    'Ipuiúna, MG',
    'Itamogi, MG',
    'Carneirinho, MG',
    'Paço do Lumiar, MA',
    'São Luís, MA',
    'Imperatriz, MA',
    'São José de Ribamar, MA',
    'Timon, MA',
    'Caxias, MA',
    'Codó, MA',
    'Açailândia, MA',
    'Bacabal, MA',
    'Balsas, MA',
    'Santa Inês, MA',
    'Barra do Corda, MA',
    'Pinheiro, MA',
    'Chapadinha, MA',
    'Buriticupu, MA',
    'Santa Luzia, MA',
    'Grajaú, MA',
    'Itapecuru Mirim, MA',
    'Coroatá, MA',
    'Barreirinhas, MA',
    'Tutóia, MA',
    'Vargem Grande, MA',
    'Viana, MA',
    'Zé Doca, MA',
    'Lago da Pedra, MA',
    'Coelho Neto, MA',
    'Presidente Dutra, MA',
    'Araioses, MA',
    'São Bento, MA',
    'Rosário, MA',
    'Estreito, MA',
    'Santa Helena, MA',
    'Tuntum, MA',
    'Amarante do Maranhão, MA',
    'Bom Jardim, MA',
    'São Mateus do Maranhão, MA',
    'Colinas, MA',
    'Pedreiras, MA',
    'Penalva, MA',
    'Santa Rita, MA',
    'Brejo, MA',
    'Turiaçu, MA',
    'Parnarama, MA',
    'Bom Jesus das Selvas, MA',
    'São Domingos do Maranhão, MA',
    'Matões, MA',
    'Monção, MA',
    'Urbano Santos, MA',
    'Pindaré-Mirim, MA',
    'Vitória do Mearim, MA',
    'Arame, MA',
    'Cururupu, MA',
    'Alto Alegre do Pindaré, MA',
    'Raposa, MA',
    'Vitorino Freire, MA',
    'Arari, MA',
    'Timbiras, MA',
    'Humberto de Campos, MA',
    'Miranda do Norte, MA',
    'Buriti, MA',
    'São Bernardo, MA',
    'Alto Alegre do Maranhão, MA',
    'Icatu, MA',
    'Anajatuba, MA',
    'Aldeias Altas, MA',
    'Itinga do Maranhão, MA',
    'Turilândia, MA',
    'São João dos Patos, MA',
    'Santa Quitéria do Maranhão, MA',
    'Pedro do Rosário, MA',
    'Governador Nunes Freire, MA',
    'Santa Luzia do Paruá, MA',
    'Porto Franco, MA',
    'Carolina, MA',
    'Carutapera, MA',
    'Buriti Bravo, MA',
    'João Lisboa, MA',
    'Matinha, MA',
    'Peritoró, MA',
    'Dom Pedro, MA',
    'São Vicente Ferrer, MA',
    'Cantanhede, MA',
    'Trizidela do Vale, MA',
    'Alcântara, MA',
    'Centro Novo do Maranhão, MA',
    'Maracaçumé, MA',
    'Paraibano, MA',
    'Bequimão, MA',
    'Pio XII, MA',
    'Nova Olinda do Maranhão, MA',
    'Paulo Ramos, MA',
    'Mirador, MA',
    'São João Batista, MA',
    'Cândido Mendes, MA',
    'Riachão, MA',
    'Magalhães de Almeida, MA',
    'Palmeirândia, MA',
    'Morros, MA',
    'Pastos Bons, MA',
    'Olho dÁgua das Cunhãs, MA',
    'Cajari, MA',
    'Formosa da Serra Negra, MA',
    'Passagem Franca, MA',
    'Presidente Sarney, MA',
    'São Raimundo das Mangabeiras, MA',
    'Barão de Grajaú, MA',
    'Pirapemas, MA',
    'São Benedito do Rio Preto, MA',
    'São João do Soter, MA',
    'Governador Edison Lobão, MA',
    'Bacuri, MA',
    'São Luís Gonzaga do Maranhão, MA',
    'Sítio Novo, MA',
    'Gonçalves Dias, MA',
    'Fortuna, MA',
    'Apicum-Açu, MA',
    'Bacabeira, MA',
    'Poção de Pedras, MA',
    'Matões do Norte, MA',
    'Jenipapo dos Vieiras, MA',
    'Mata Roma, MA',
    'Esperantinópolis, MA',
    'Maranhãozinho, MA',
    'Bom Lugar, MA',
    'Conceição do Lago-Açu, MA',
    'Lago Verde, MA',
    'Paulino Neves, MA',
    'Joselândia, MA',
    'Santo Amaro do Maranhão, MA',
    'Itaipava do Grajaú, MA',
    'Anapurus, MA',
    'São João do Carú, MA',
    'Araguanã, MA',
    'Primeira Cruz, MA',
    'Buritirana, MA',
    'Mirinzal, MA',
    'Olinda Nova do Maranhão, MA',
    'Cidelândia, MA',
    'Nina Rodrigues, MA',
    'Governador Eugênio Barros, MA',
    'Campestre do Maranhão, MA',
    'Santo Antônio dos Lopes, MA',
    'Igarapé do Meio, MA',
    'Peri Mirim, MA',
    'Satubinha, MA',
    'Senador La Rocque, MA',
    'Centro do Guilherme, MA',
    'Vila Nova dos Martírios, MA',
    'Santana do Maranhão, MA',
    'Presidente Juscelino, MA',
    'Davinópolis, MA',
    'São Pedro da Água Branca, MA',
    'Água Doce do Maranhão, MA',
    'Fortaleza dos Nogueiras, MA',
    'Loreto, MA',
    'Axixá, MA',
    'São Francisco do Maranhão, MA',
    'Godofredo Viana, MA',
    'São Francisco do Brejão, MA',
    'Guimarães, MA',
    'Lima Campos, MA',
    'Lagoa Grande do Maranhão, MA',
    'Igarapé Grande, MA',
    'Duque Bacelar, MA',
    'Bela Vista do Maranhão, MA',
    'Presidente Vargas, MA',
    'Senador Alexandre Costa, MA',
    'Lagoa do Mato, MA',
    'Cajapió, MA',
    'Alto Parnaíba, MA',
    'São João do Paraíso, MA',
    'Capinzal do Norte, MA',
    'Governador Archer, MA',
    'Lago do Junco, MA',
    'Cedral, MA',
    'Sucupira do Norte, MA',
    'Fernando Falcão, MA',
    'Jatobá, MA',
    'Serrano do Maranhão, MA',
    'Governador Newton Bello, MA',
    'Goiânia, GO',
    'Aparecida de Goiânia, GO',
    'Anápolis, GO',
    'Rio Verde, GO',
    'Águas Lindas de Goiás, GO',
    'Luziânia, GO',
    'Valparaíso de Goiás, GO',
    'Trindade, GO',
    'Formosa, GO',
    'Senador Canedo, GO',
    'Novo Gama, GO',
    'Catalão, GO',
    'Itumbiara, GO',
    'Jataí, GO',
    'Caldas Novas, GO',
    'Planaltina, GO',
    'Santo Antônio do Descoberto, GO',
    'Cidade Ocidental, GO',
    'Goianésia, GO',
    'Mineiros, GO',
    'Cristalina, GO',
    'Inhumas, GO',
    'Jaraguá, GO',
    'Quirinópolis, GO',
    'Niquelândia, GO',
    'Morrinhos, GO',
    'Goianira, GO',
    'Porangatu, GO',
    'Itaberaí, GO',
    'Uruaçu, GO',
    'Santa Helena de Goiás, GO',
    'Posse, GO',
    'Padre Bernardo, GO',
    'São Luís de Montes Belos, GO',
    'Goiatuba, GO',
    'Pires do Rio, GO',
    'Iporá, GO',
    'Bela Vista de Goiás, GO',
    'Nerópolis, GO',
    'Palmeiras de Goiás, GO',
    'Minaçu, GO',
    'Alexânia, GO',
    'Ipameri, GO',
    'Bom Jesus de Goiás, GO',
    'Itapuranga, GO',
    'Pirenópolis, GO',
    'Piracanjuba, GO',
    'Itapaci, GO',
    'Acreúna, GO',
    'Hidrolândia, GO',
    'Ceres, GO',
    'Goiás, GO',
    'Anicuns, GO',
    'São Miguel do Araguaia, GO',
    'São Simão, GO',
    'Silvânia, GO',
    'Abadiânia, GO',
    'Cocalzinho de Goiás, GO',
    'Aragarças, GO',
    'Campos Belos, GO',
    'Rubiataba, GO',
    'Caiapônia, GO',
    'Jussara, GO',
    'Pontalina, GO',
    'Flores de Goiás, GO',
    'Crixás, GO',
    'Caçu, GO',
    'Mozarlândia, GO',
    'Indiara, GO',
    'Orizona, GO',
    'Maurilândia, GO',
    'São João dAliança, GO',
    'Iaciara, GO',
    'Guapó, GO',
    'Vianópolis, GO',
    'Montividiu, GO',
    'Uruana, GO',
    'Firminópolis, GO',
    'São Domingos, GO',
    'Nova Crixás, GO',
    'Campinorte, GO',
    'Cachoeira Alta, GO',
    'Edéia, GO',
    'Barro Alto, GO',
    'Corumbá de Goiás, GO',
    'Goianápolis, GO',
    'Paraúna, GO',
    'Rialma, GO',
    'Chapadão do Céu, GO',
    'Aragoiânia, GO',
    'Aruanã, GO',
    'Carmo do Rio Verde, GO',
    'Petrolina de Goiás, GO',
    'Paranaiguara, GO',
    'Nova Veneza, GO',
    'Piranhas, GO',
    'Bonfinópolis, GO',
    'Serra, ES',
    'Vila Velha, ES',
    'Cariacica, ES',
    'Vitória, ES',
    'Cachoeiro de Itapemirim, ES',
    'Linhares, ES',
    'São Mateus, ES',
    'Guarapari, ES',
    'Colatina, ES',
    'Aracruz, ES',
    'Viana, ES',
    'Nova Venécia, ES',
    'Barra de São Francisco, ES',
    'Santa Maria de Jetibá, ES',
    'Marataízes, ES',
    'São Gabriel da Palha, ES',
    'Castelo, ES',
    'Itapemirim, ES',
    'Domingos Martins, ES',
    'Jaguaré, ES',
    'Conceição da Barra, ES',
    'Guaçuí, ES',
    'Sooretama, ES',
    'Baixo Guandu, ES',
    'Afonso Cláudio, ES',
    'Anchieta, ES',
    'Alegre, ES',
    'Iúna, ES',
    'Pinheiros, ES',
    'Ibatiba, ES',
    'Pedro Canário, ES',
    'Venda Nova do Imigrante, ES',
    'Mimoso do Sul, ES',
    'Santa Teresa, ES',
    'Pancas, ES',
    'Ecoporanga, ES',
    'Piúma, ES',
    'Fundão, ES',
    'Vargem Alta, ES',
    'Rio Bananal, ES',
    'Montanha, ES',
    'Muniz Freire, ES',
    'Marechal Floriano, ES',
    'João Neiva, ES',
    'Mantenópolis, ES',
    'Muqui, ES',
    'Boa Esperança, ES',
    'Alfredo Chaves, ES',
    'Iconha, ES',
    'Vila Valério, ES',
    'Itaguaçu, ES',
    'Irupi, ES',
    'Marilândia, ES',
    'Governador Lindenberg, ES',
    'Conceição do Castelo, ES',
    'Ibiraçu, ES',
    'São Roque do Canaã, ES',
    'Brejetuba, ES',
    'Jerônimo Monteiro, ES',
    'Atílio Vivácqua, ES',
    'Santa Leopoldina, ES',
    'Presidente Kennedy, ES',
    'Rio Novo do Sul, ES',
    'Laranja da Terra, ES',
    'Água Doce do Norte, ES',
    'São José do Calçado, ES',
    'Itarana, ES',
    'Brasília, DF',
    'Fortaleza, CE',
    'Caucaia, CE',
    'Juazeiro do Norte, CE',
    'Maracanaú, CE',
    'Sobral, CE',
    'Crato, CE',
    'Itapipoca, CE',
    'Maranguape, CE',
    'Iguatu, CE',
    'Quixadá, CE',
    'Pacatuba, CE',
    'Quixeramobim, CE',
    'Aquiraz, CE',
    'Russas, CE',
    'Canindé, CE',
    'Tianguá, CE',
    'Aracati, CE',
    'Crateús, CE',
    'Pacajus, CE',
    'Cascavel, CE',
    'Horizonte, CE',
    'Icó, CE',
    'Camocim, CE',
    'Acaraú, CE',
    'Viçosa do Ceará, CE',
    'Barbalha, CE',
    'Morada Nova, CE',
    'Limoeiro do Norte, CE',
    'Tauá, CE',
    'Trairi, CE',
    'Granja, CE',
    'Eusébio, CE',
    'Acopiara, CE',
    'Boa Viagem, CE',
    'Beberibe, CE',
    'Itapajé, CE',
    'Brejo Santo, CE',
    'São Gonçalo do Amarante, CE',
    'Mauriti, CE',
    'São Benedito, CE',
    'Amontada, CE',
    'Mombaça, CE',
    'Santa Quitéria, CE',
    'Pedra Branca, CE',
    'Itarema, CE',
    'Ipu, CE',
    'Várzea Alegre, CE',
    'Guaraciaba do Norte, CE',
    'Massapê, CE',
    'Itaitinga, CE',
    'Ipueiras, CE',
    'Pentecoste, CE',
    'Baturité, CE',
    'Missão Velha, CE',
    'Paracuru, CE',
    'Ubajara, CE',
    'Jaguaribe, CE',
    'Jaguaruana, CE',
    'Paraipaba, CE',
    'Bela Cruz, CE',
    'Santana do Acaraú, CE',
    'Nova Russas, CE',
    'Tabuleiro do Norte, CE',
    'Lavras da Mangabeira, CE',
    'Parambu, CE',
    'Redenção, CE',
    'Novo Oriente, CE',
    'Marco, CE',
    'Campos Sales, CE',
    'Milagres, CE',
    'Jardim, CE',
    'Caririaçu, CE',
    'Aracoiaba, CE',
    'Guaiúba, CE',
    'Tamboril, CE',
    'Independência, CE',
    'Ocara, CE',
    'Cedro, CE',
    'Senador Pompeu, CE',
    'Ibiapina, CE',
    'Cruz, CE',
    'Jucás, CE',
    'Forquilha, CE',
    'Aurora, CE',
    'Irauçuba, CE',
    'Assaré, CE',
    'Coreaú, CE',
    'Caridade, CE',
    'Barro, CE',
    'Morrinhos, CE',
    'Barreira, CE',
    'Quixeré, CE',
    'Uruburetama, CE',
    'Itatira, CE',
    'Araripe, CE',
    'Orós, CE',
    'Quiterianópolis, CE',
    'Catarina, CE',
    'Pindoretama, CE',
    'Itapiúna, CE',
    'Jijoca de Jericoacoara, CE',
    'Chorozinho, CE',
    'Icapuí, CE',
    'Hidrolândia, CE',
    'Madalena, CE',
    'Umirim, CE',
    'Tejuçuoca, CE',
    'Farias Brito, CE',
    'Cariús, CE',
    'Varjota, CE',
    'Cariré, CE',
    'Solonópole, CE',
    'Banabuiú, CE',
    'Reriutaba, CE',
    'Croatá, CE',
    'Jaguaretama, CE',
    'Capistrano, CE',
    'Carnaubal, CE',
    'Santana do Cariri, CE',
    'Aiuaba, CE',
    'Monsenhor Tabosa, CE',
    'Piquet Carneiro, CE',
    'Fortim, CE',
    'Salitre, CE',
    'Tururu, CE',
    'Pereiro, CE',
    'Quixelô, CE',
    'Alto Santo, CE',
    'Nova Olinda, CE',
    'Saboeiro, CE',
    'Meruoca, CE',
    'Acarape, CE',
    'Barroquinha, CE',
    'Porteiras, CE',
    'Apuiarés, CE',
    'Mucambo, CE',
    'Graça, CE',
    'Iracema, CE',
    'Frecheirinha, CE',
    'Uruoca, CE',
    'Miraíma, CE',
    'Choró, CE',
    'Palmácia, CE',
    'Ibaretama, CE',
    'Milhã, CE',
    'Chaval, CE',
    'São Luís do Curu, CE',
    'Ibicuitinga, CE',
    'Ipaumirim, CE',
    'Poranga, CE',
    'Pacoti, CE',
    'Paramoti, CE',
    'Abaiara, CE',
    'Alcântaras, CE',
    'Aratuba, CE',
    'Ipaporanga, CE',
    'Jaguaribara, CE',
    'Martinópole, CE',
    'Groaíras, CE',
    'Potengi, CE',
    'Mulungu, CE',
    'Pires Ferreira, CE',
    'Ararendá, CE',
    'Catunda, CE',
    'Rodelas, BA',
    'Ibiassucê, BA',
    'Vera Cruz, BA',
    'Coronel João Sá, BA',
    'Salvador, BA',
    'Feira de Santana, BA',
    'Vitória da Conquista, BA',
    'Camaçari, BA',
    'Juazeiro, BA',
    'Itabuna, BA',
    'Lauro de Freitas, BA',
    'Teixeira de Freitas, BA',
    'Barreiras, BA',
    'Ilhéus, BA',
    'Jequié, BA',
    'Alagoinhas, BA',
    'Porto Seguro, BA',
    'Simões Filho, BA',
    'Paulo Afonso, BA',
    'Eunápolis, BA',
    'Santo Antônio de Jesus, BA',
    'Valença, BA',
    'Luís Eduardo Magalhães, BA',
    'Candeias, BA',
    'Guanambi, BA',
    'Dias dÁvila, BA',
    'Serrinha, BA',
    'Jacobina, BA',
    'Senhor do Bonfim, BA',
    'Itapetinga, BA',
    'Irecê, BA',
    'Casa Nova, BA',
    'Campo Formoso, BA',
    'Bom Jesus da Lapa, BA',
    'Brumado, BA',
    'Conceição do Coité, BA',
    'Itaberaba, BA',
    'Itamaraju, BA',
    'Cruz das Almas, BA',
    'Euclides da Cunha, BA',
    'Santo Amaro, BA',
    'Ipirá, BA',
    'Catu, BA',
    'Jaguaquara, BA',
    'Araci, BA',
    'Barra, BA',
    'Ribeira do Pombal, BA',
    'Santo Estêvão, BA',
    'Caetité, BA',
    'Tucano, BA',
    'Macaúbas, BA',
    'Monte Santo, BA',
    'Mata de São João, BA',
    'Poções, BA',
    'Xique-Xique, BA',
    'Livramento de Nossa Senhora, BA',
    'Ipiaú, BA',
    'Maragogipe, BA',
    'São Sebastião do Passé, BA',
    'Seabra, BA',
    'Nova Viçosa, BA',
    'Mucuri, BA',
    'Entre Rios, BA',
    'Remanso, BA',
    'Sento Sé, BA',
    'Rio Real, BA',
    'Jeremoabo, BA',
    'Inhambupe, BA',
    'São Francisco do Conde, BA',
    'Pojuca, BA',
    'Santa Maria da Vitória, BA',
    'São Gonçalo dos Campos, BA',
    'Esplanada, BA',
    'Santaluz, BA',
    'Amargosa, BA',
    'Itapicuru, BA',
    'Itiúba, BA',
    'Riacho de Santana, BA',
    'Morro do Chapéu, BA',
    'Camamu, BA',
    'Pilão Arcado, BA',
    'Curaçá, BA',
    'Cansanção, BA',
    'São Desidério, BA',
    'Jaguarari, BA',
    'Cachoeira, BA',
    'Conceição do Jacuípe, BA',
    'Riachão do Jacuípe, BA',
    'Gandu, BA',
    'Cícero Dantas, BA',
    'Paratinga, BA',
    'Correntina, BA',
    'Camacan, BA',
    'Serra do Ramalho, BA',
    'Capim Grosso, BA',
    'Itabela, BA',
    'Ruy Barbosa, BA',
    'Barra do Choça, BA',
    'Canavieiras, BA',
    'Muritiba, BA',
    'Irará, BA',
    'Paripiranga, BA',
    'Carinhanha, BA',
    'Valente, BA',
    'Itacaré, BA',
    'Ituberá, BA',
    'Campo Alegre de Lourdes, BA',
    'Nazaré, BA',
    'Santa Rita de Cássia, BA',
    'Olindina, BA',
    'Presidente Tancredo Neves, BA',
    'Prado, BA',
    'Santa Cruz Cabrália, BA',
    'Quijingue, BA',
    'Ubatã, BA',
    'Lapão, BA',
    'Mundo Novo, BA',
    'Ibotirama, BA',
    'Nova Soure, BA',
    'Iguaí, BA',
    'Santana, BA',
    'Planalto, BA',
    'Canarana, BA',
    'Castro Alves, BA',
    'Conde, BA',
    'Formosa do Rio Preto, BA',
    'Miguel Calmon, BA',
    'Iraquara, BA',
    'João Dourado, BA',
    'Queimadas, BA',
    'Piritiba, BA',
    'Amélia Rodrigues, BA',
    'Cândido Sales, BA',
    'Laje, BA',
    'Uauá, BA',
    'Iaçu, BA',
    'Belmonte, BA',
    'Ibirapitanga, BA',
    'Caculé, BA',
    'Sobradinho, BA',
    'Conceição da Feira, BA',
    'Medeiros Neto, BA',
    'Rafael Jambeiro, BA',
    'Teofilândia, BA',
    'Alcobaça, BA',
    'Itambé, BA',
    'Itaparica, BA',
    'Coração de Maria, BA',
    'Mutuípe, BA',
    'Riachão das Neves, BA',
    'Caravelas, BA',
    'Palmas de Monte Alto, BA',
    'Oliveira dos Brejinhos, BA',
    'Paramirim, BA',
    'Madre de Deus, BA',
    'Boquira, BA',
    'Taperoá, BA',
    'Buritirama, BA',
    'Anagé, BA',
    'Crisópolis, BA',
    'Ibicaraí, BA',
    'São Felipe, BA',
    'Santa Bárbara, BA',
    'Wenceslau Guimarães, BA',
    'Governador Mangabeira, BA',
    'Maraú, BA',
    'Abaré, BA',
    'Guaratinga, BA',
    'Baixa Grande, BA',
    'Itororó, BA',
    'Tanhaçu, BA',
    'Uruçuca, BA',
    'Itajuípe, BA',
    'Barra da Estiva, BA',
    'Pindobaçu, BA',
    'Ibicoara, BA',
    'Maracás, BA',
    'Itarantim, BA',
    'Ubaíra, BA',
    'Antas, BA',
    'Umburanas, BA',
    'Utinga, BA',
    'Itanhém, BA',
    'Jaguaripe, BA',
    'Ituaçu, BA',
    'Macarani, BA',
    'Cabaceiras do Paraguaçu, BA',
    'Cocos, BA',
    'São Gabriel, BA',
    'Cairu, BA',
    'Ubaitaba, BA',
    'Mirangaba, BA',
    'Cafarnaum, BA',
    'Mairi, BA',
    'Boa Vista do Tupim, BA',
    'Ibipeba, BA',
    'Buerarema, BA',
    'Una, BA',
    'Aporá, BA',
    'Fátima, BA',
    'Ourolândia, BA',
    'Tanque Novo, BA',
    'Sapeaçu, BA',
    'Cipó, BA',
    'Sátiro Dias, BA',
    'Central, BA',
    'Serra Dourada, BA',
    'Adustina, BA',
    'Souto Soares, BA',
    'Condeúba, BA',
    'Água Fria, BA',
    'Conceição do Almeida, BA',
    'Ibititá, BA',
    'Belo Campo, BA',
    'Bonito, BA',
    'Tapiramutá, BA',
    'Malhada, BA',
    'Piatã, BA',
    'Canudos, BA',
    'Pedro Alexandre, BA',
    'Urandi, BA',
    'Nova Canaã, BA',
    'Ibitiara, BA',
    'Filadélfia, BA',
    'Pindaí, BA',
    'Ibicuí, BA',
    'Barrocas, BA',
    'Itaeté, BA',
    'Coaraci, BA',
    'América Dourada, BA',
    'Salinas da Margarida, BA',
    'Tremedal, BA',
    'Biritinga, BA',
    'Encruzilhada, BA',
    'Lagoa Real, BA',
    'Igaporã, BA',
    'São Félix do Coribe, BA',
    'Rio do Antônio, BA',
    'Novo Triunfo, BA',
    'Glória, BA',
    'Jussara, BA',
    'Acajutiba, BA',
    'Presidente Dutra, BA',
    'Barro Alto, BA',
    'Teolândia, BA',
    'Ibipitanga, BA',
    'Jacaraci, BA',
    'São Félix, BA',
    'Ponto Novo, BA',
    'Caetanos, BA',
    'Itaguaçu da Bahia, BA',
    'Ribeira do Amparo, BA',
    'Itatim, BA',
    'Retirolândia, BA',
    'Jiquiriçá, BA',
    'Serra Preta, BA',
    'Boninal, BA',
    'Ibirataia, BA',
    'Andorinha, BA',
    'Candiba, BA',
    'Itagibá, BA',
    'Ipecaetá, BA',
    'Nilo Peçanha, BA',
    'Brejões, BA',
    'Várzea da Roça, BA',
    'Coribe, BA',
    'Cristópolis, BA',
    'Baianópolis, BA',
    'Santa Brígida, BA',
    'Angical, BA',
    'Uibaí, BA',
    'Mansidão, BA',
    'Cotegipe, BA',
    'Mascote, BA',
    'Pé de Serra, BA',
    'Serrolândia, BA',
    'Caldeirão Grande, BA',
    'Banzaê, BA',
    'Nordestina, BA',
    'Barra do Mendes, BA',
    'Andaraí, BA',
    'Sítio do Mato, BA',
    'Terra Nova, BA',
    'Saúde, BA',
    'Igrapiúna, BA',
    'Aracatu, BA',
    'Heliópolis, BA',
    'Manoel Vitorino, BA',
    'Rio de Contas, BA',
    'Novo Horizonte, BA',
    'Várzea Nova, BA',
    'Tabocas do Brejo Velho, BA',
    'Itiruçu, BA',
    'Matina, BA',
    'Licínio de Almeida, BA',
    'Santa Luzia, BA',
    'Dom Basílio, BA',
    'Araçás, BA',
    'Saubara, BA',
    'Itagi, BA',
    'Wanderley, BA',
    'Mortugaba, BA',
    'Boa Nova, BA',
    'Presidente Jânio Quadros, BA',
    'Antônio Gonçalves, BA',
    'São Miguel das Matas, BA',
    'Rio do Pires, BA',
    'Antônio Cardoso, BA',
    'Capela do Alto Alegre, BA',
    'Lençóis, BA',
    'Sebastião Laranjeiras, BA',
    'Aramari, BA',
    'Muquém do São Francisco, BA',
    'Anguera, BA',
    'Macajuba, BA',
    'Gentio do Ouro, BA',
    'Chorrochó, BA',
    'Aurelino Leal, BA',
    'Iuiu, BA',
    'Arataca, BA',
    'Milagres, BA',
    'Jandaíra, BA',
    'Brotas de Macaúbas, BA',
    'Brejolândia, BA',
    'Santa Inês, BA',
    'São José do Jacuípe, BA',
    'Floresta Azul, BA',
    'Santa Terezinha, BA',
    'Érico Cardoso, BA',
    'Jitaúna, BA',
    'Mulungu do Morro, BA',
    'Marcionílio Souza, BA',
    'Pintadas, BA',
    'Dário Meira, BA',
    'Maiquinique, BA',
    'Itapitanga, BA',
    'Piripá, BA',
    'Itapebi, BA',
    'Botuporã, BA',
    'Piraí do Norte, BA',
    'Macapá, AP',
    'Santana, AP',
    'Laranjal do Jari, AP',
    'Oiapoque, AP',
    'Porto Grande, AP',
    'Mazagão, AP',
    'Tartarugalzinho, AP',
    'Pedra Branca do Amapari, AP',
    'Vitória do Jari, AP',
    'Calçoene, AP',
    'Tabatinga, AM',
    'Lábrea, AM',
    'Benjamin Constant, AM',
    'Manaquiri, AM',
    'Santa Isabel do Rio Negro, AM',
    'Urucurituba, AM',
    'Guajará, AM',
    'Urucará, AM',
    'Caapiranga, AM',
    'Jutaí, AM',
    'Parintins, AM',
    'Manaus, AM',
    'Itacoatiara, AM',
    'Manacapuru, AM',
    'Coari, AM',
    'Maués, AM',
    'Tefé, AM',
    'Manicoré, AM',
    'Humaitá, AM',
    'Iranduba, AM',
    'São Gabriel da Cachoeira, AM',
    'Borba, AM',
    'Autazes, AM',
    'São Paulo de Olivença, AM',
    'Careiro, AM',
    'Nova Olinda do Norte, AM',
    'Presidente Figueiredo, AM',
    'Eirunepé, AM',
    'Boca do Acre, AM',
    'Rio Preto da Eva, AM',
    'Barreirinha, AM',
    'Careiro da Várzea, AM',
    'Ipixuna, AM',
    'Codajás, AM',
    'Carauari, AM',
    'Barcelos, AM',
    'Novo Aripuanã, AM',
    'Apuí, AM',
    'Anori, AM',
    'Nhamundá, AM',
    'Santo Antônio do Içá, AM',
    'Atalaia do Norte, AM',
    'Envira, AM',
    'Beruri, AM',
    'Novo Airão, AM',
    'Boa Vista do Ramos, AM',
    'Pauini, AM',
    'Tonantins, AM',
    'Maraã, AM',
    'Tapauá, AM',
    'Fonte Boa, AM',
    'Alvarães, AM',
    'Canutama, AM',
    'Juruá, AM',
    'São Sebastião do Uatumã, AM',
    'Anamã, AM',
    'Uarini, AM',
    'Amaturá, AM',
    'Maceió, AL',
    'Arapiraca, AL',
    'Rio Largo, AL',
    'Palmeira dos Índios, AL',
    'União dos Palmares, AL',
    'Penedo, AL',
    'São Miguel dos Campos, AL',
    'Campo Alegre, AL',
    'Coruripe, AL',
    'Marechal Deodoro, AL',
    'Delmiro Gouveia, AL',
    'Santana do Ipanema, AL',
    'Atalaia, AL',
    'Teotônio Vilela, AL',
    'Girau do Ponciano, AL',
    'Pilar, AL',
    'São Luís do Quitunde, AL',
    'São Sebastião, AL',
    'Maragogi, AL',
    'São José da Tapera, AL',
    'Limoeiro de Anadia, AL',
    'Murici, AL',
    'Traipu, AL',
    'Boca da Mata, AL',
    'Porto Calvo, AL',
    'Viçosa, AL',
    'Igaci, AL',
    'Piranhas, AL',
    'Mata Grande, AL',
    'Junqueiro, AL',
    'Igreja Nova, AL',
    'Matriz de Camaragibe, AL',
    'Craíbas, AL',
    'Pão de Açúcar, AL',
    'Joaquim Gomes, AL',
    'São José da Laje, AL',
    'Feira Grande, AL',
    'Colônia Leopoldina, AL',
    'Olho dÁgua das Flores, AL',
    'Cajueiro, AL',
    'Água Branca, AL',
    'Taquarana, AL',
    'Porto Real do Colégio, AL',
    'Major Isidoro, AL',
    'Batalha, AL',
    'Inhapi, AL',
    'Estrela de Alagoas, AL',
    'Messias, AL',
    'Piaçabuçu, AL',
    'Canapi, AL',
    'Lagoa da Canoa, AL',
    'Anadia, AL',
    'Capela, AL',
    'Barra de Santo Antônio, AL',
    'Ibateguara, AL',
    'Passo de Camaragibe, AL',
    'Poço das Trincheiras, AL',
    'Satuba, AL',
    'Senador Rui Palmeira, AL',
    'Paripueira, AL',
    'Maribondo, AL',
    'Novo Lino, AL',
    'Flexeiras, AL',
    'Olivença, AL',
    'Ouro Branco, AL',
    'Jequiá da Praia, AL',
    'Quebrangulo, AL',
    'Dois Riachos, AL',
    'Cacimbinhas, AL',
    'Santana do Mundaú, AL',
    'Coité do Nóia, AL',
    'Pariconha, AL',
    'Branquinha, AL',
    'Rio Branco, AC',
    'Cruzeiro do Sul, AC',
    'Sena Madureira, AC',
    'Tarauacá, AC',
    'Feijó, AC',
    'Brasiléia, AC',
    'Senador Guiomard, AC',
    'Plácido de Castro, AC',
    'Xapuri, AC',
    'Rodrigues Alves, AC',
    'Marechal Thaumaturgo, AC',
    'Mâncio Lima, AC',
    'Porto Acre, AC',
    'Epitaciolândia, AC',
    'Acrelândia, AC',
    'Porto Walter, AC',
    'Capixaba, AC',
    'Bujari, AC',
  ];
}
